'use client';

import { useState } from 'react';

const services = [
  { icon: '◉', title: 'Study Abroad', text: 'Find the country, university and course that fits your ambitions.' },
  { icon: '✚', title: 'China Treatment Package', text: 'Complete care coordination—from hospital to stay, travel and support.' },
  { icon: '⌁', title: 'Student Visa', text: 'Clear, careful application guidance for a confident next step.' },
  { icon: '↗', title: 'Work Visa', text: 'Practical support for professionals building careers abroad.' },
  { icon: '◎', title: 'Immigration Support', text: 'Plan your global move with clarity, documentation and care.' },
  { icon: '✦', title: 'Career Counseling', text: 'Turn your strengths into a focused international pathway.' }
];
const countries = [
  { name: 'China', code: 'CN', color: 'bg-[#B42A1D]' }, { name: 'Australia', code: 'AU', color: 'bg-[#304132]' },
  { name: 'Canada', code: 'CA', color: 'bg-[#4F7E6A]' }, { name: 'United Kingdom', code: 'UK', color: 'bg-[#90281B]' },
  { name: 'Malaysia', code: 'MY', color: 'bg-[#FF6638]' }, { name: 'Europe', code: 'EU', color: 'bg-[#304132]' }
];
const faqs = [
  ['What does the China Treatment Package include?', 'We coordinate hospital selection, appointments, accommodation, local transportation, interpreter support where needed, visa assistance and on-ground guidance—so you can focus on care.'],
  ['Which countries can I apply to for study?', 'We currently guide students for China, Australia, Canada, the United Kingdom, Malaysia and selected European destinations.'],
  ['Do you help with scholarships?', 'Yes. We help identify relevant opportunities and prepare a stronger, more complete scholarship application.'],
  ['How do I begin my consultation?', 'Simply send us a message, call our team or use the form below. We will arrange a consultation around your goals.']
];

function Logo() { return <a href="#home" className="flex items-center gap-3" aria-label="Arshi Global Care home"><span className="grid h-10 w-10 place-items-center rounded-xl bg-arshi-red text-xl font-bold text-white">A</span><span className="leading-tight"><b className="block tracking-[.13em] text-arshi-ink">ARSHI</b><small className="block text-[9px] font-semibold tracking-[.22em] text-arshi-red">GLOBAL CARE</small></span></a>; }
function Arrow() { return <span aria-hidden="true">→</span>; }

export default function Home() {
  const [menu, setMenu] = useState(false);
  const [sent, setSent] = useState(false);
  return <main id="home">
    <div className="bg-arshi-ink px-5 py-2 text-center text-xs font-medium text-white sm:text-sm">Your trusted bridge to global education, healthcare & opportunity <a href="#contact" className="ml-2 underline underline-offset-4">Talk to an expert</a></div>
    <header className="sticky top-0 z-40 border-b border-stone-100 bg-white/95 backdrop-blur">
      <div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 lg:px-8"><Logo />
        <nav className="hidden items-center gap-7 text-sm font-semibold lg:flex"><a href="#services" className="hover:text-arshi-red">Services</a><a href="#process" className="hover:text-arshi-red">How it works</a><a href="#destinations" className="hover:text-arshi-red">Destinations</a><a href="#stories" className="hover:text-arshi-red">Stories</a><a href="#contact" className="rounded-lg bg-arshi-red px-5 py-3 text-white transition hover:bg-arshi-wine">Free Consultation</a></nav>
        <button className="rounded-lg border border-stone-200 p-2 lg:hidden" onClick={() => setMenu(!menu)} aria-label="Open menu">☰</button>
      </div>
      {menu && <nav className="border-t bg-white px-5 pb-5 pt-2 lg:hidden"><div className="grid gap-3 text-sm font-semibold"><a href="#services" onClick={() => setMenu(false)}>Services</a><a href="#process" onClick={() => setMenu(false)}>How it works</a><a href="#contact" onClick={() => setMenu(false)}>Contact us</a></div></nav>}
    </header>

    <section className="hero-glow relative overflow-hidden bg-[#fffaf8]"><div className="grid-dots absolute left-0 top-0 h-full w-1/3 opacity-50" /><div className="mx-auto grid min-h-[610px] max-w-7xl items-center gap-10 px-5 py-16 lg:grid-cols-[.96fr_1.04fr] lg:px-8 lg:py-20">
      <div className="relative z-10"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#B42A1D]/15 bg-white px-4 py-2 text-xs font-bold text-arshi-red"><span className="h-2 w-2 rounded-full bg-arshi-red" /> GUIDANCE THAT GOES BEYOND BORDERS</div><h1 className="serif max-w-2xl text-5xl leading-[1.06] text-arshi-ink sm:text-6xl lg:text-7xl">Your next chapter <em className="text-arshi-red not-italic">begins here.</em></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#58665a]">From a world-class education to coordinated care in China, we make complex global journeys feel personal, clear and possible.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#contact" className="shimmer rounded-lg bg-arshi-red px-6 py-4 text-center font-bold text-white shadow-lg shadow-[#B42A1D]/15 transition hover:bg-arshi-wine">Book Free Consultation <Arrow /></a><a href="#services" className="rounded-lg border border-arshi-ink/15 bg-white px-6 py-4 text-center font-bold text-arshi-ink transition hover:border-arshi-red hover:text-arshi-red">Explore services <Arrow /></a></div><div className="mt-12 flex gap-8 border-t border-stone-200 pt-6"><div><b className="block text-2xl text-arshi-red">6+</b><span className="text-xs font-medium text-[#667168]">Global destinations</span></div><div><b className="block text-2xl text-arshi-red">1:1</b><span className="text-xs font-medium text-[#667168]">Personal guidance</span></div><div><b className="block text-2xl text-arshi-red">End-to-end</b><span className="text-xs font-medium text-[#667168]">Journey support</span></div></div></div>
      <div className="relative"><div className="absolute -right-8 -top-8 h-32 w-32 rounded-full border-[18px] border-arshi-orange/20" /><div className="relative overflow-hidden rounded-[26px] border-8 border-white shadow-2xl shadow-[#304132]/10"><img src="/images/arshi-hero.png" alt="Student receiving global education guidance in a modern office" className="h-[440px] w-full object-cover lg:h-[510px]" /></div><div className="absolute -bottom-5 -left-3 max-w-[220px] rounded-xl border border-stone-100 bg-white p-4 shadow-xl"><div className="mb-2 flex text-arshi-orange">★★★★★</div><p className="text-sm font-semibold leading-5">“Careful guidance at every important step.”</p><p className="mt-2 text-xs text-stone-500">— Our promise to you</p></div></div>
    </div></section>

    <section className="border-y border-stone-100 bg-white py-6"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-x-10 gap-y-4 px-5 text-xs font-bold tracking-[.12em] text-[#718077]"><span>EDUCATION</span><span className="text-arshi-red">✦</span><span>HEALTHCARE FACILITATION</span><span className="text-arshi-red">✦</span><span>GLOBAL MOBILITY</span><span className="text-arshi-red">✦</span><span>CAREER PLANNING</span></div></section>

    <section id="services" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold tracking-[.18em] text-arshi-red">WHAT WE DO</p><h2 className="serif mt-3 text-4xl text-arshi-ink sm:text-5xl">One trusted team.<br />Many possibilities.</h2></div><p className="max-w-sm text-[#617064]">Expertly connected services for the moments that change your life.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map((s, i) => <article key={s.title} className={`group rounded-xl border p-7 transition duration-300 hover:-translate-y-1 hover:border-arshi-red hover:shadow-xl hover:shadow-[#304132]/5 ${i === 1 ? 'border-[#B42A1D]/25 bg-[#fff6f3]' : 'border-stone-200 bg-white'}`}><span className="grid h-11 w-11 place-items-center rounded-lg bg-arshi-ink text-xl text-white">{s.icon}</span><h3 className="mt-6 text-xl font-bold text-arshi-ink">{s.title}</h3><p className="mt-3 min-h-[48px] text-sm leading-6 text-[#657167]">{s.text}</p><a href="#contact" className="mt-6 inline-block text-sm font-bold text-arshi-red">Learn more <Arrow /></a></article>)}</div></section>

    <section className="bg-arshi-ink py-24 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[1fr_1.2fr] lg:px-8"><div><p className="text-sm font-bold tracking-[.18em] text-arshi-peach">WHY ARSHI</p><h2 className="serif mt-3 text-4xl sm:text-5xl">Serious expertise.<br />Genuine care.</h2><p className="mt-6 max-w-md leading-7 text-[#D8E3DC]">Every journey is different. We listen first, bring the right expertise, then stay close throughout the process.</p><a href="#contact" className="mt-8 inline-block rounded-lg border border-white/30 px-5 py-3 font-bold transition hover:bg-white hover:text-arshi-ink">Meet our team <Arrow /></a></div><div className="grid gap-px overflow-hidden rounded-xl border border-white/10 bg-white/10 sm:grid-cols-2">{['Experienced Consultants','Personalized Guidance','Trusted Partners','End-to-End Support','Transparent Process','A Human Approach'].map((x, i) => <div key={x} className="bg-arshi-ink p-6"><span className="text-arshi-peach">0{i + 1}</span><h3 className="mt-8 text-lg font-bold">{x}</h3><p className="mt-2 text-sm leading-6 text-[#C3D0C7]">Thoughtful expertise designed around your unique situation.</p></div>)}</div></div></section>

    <section id="process" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="text-center"><p className="text-sm font-bold tracking-[.18em] text-arshi-red">A CLEARER WAY FORWARD</p><h2 className="serif mt-3 text-4xl text-arshi-ink sm:text-5xl">Your journey, made simple.</h2></div><div className="mt-14 grid gap-5 md:grid-cols-3 lg:grid-cols-6">{['Consultation','Documentation','Application','Approval','Travel','Ongoing Support'].map((x, i) => <div key={x} className="relative text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[#fff0eb] font-bold text-arshi-red">0{i + 1}</span><h3 className="mt-4 text-sm font-bold">{x}</h3>{i < 5 && <span className="absolute left-[61%] top-6 hidden h-px w-[78%] bg-[#ED9279] lg:block" />}</div>)}</div></section>

    <section id="destinations" className="bg-[#fff8f5] py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold tracking-[.18em] text-arshi-red">WHERE POSSIBILITY LIVES</p><h2 className="serif mt-3 text-4xl text-arshi-ink sm:text-5xl">Find your place in the world.</h2></div><a href="#contact" className="font-bold text-arshi-red">Talk destinations <Arrow /></a></div><div className="mt-12 grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-6">{countries.map(c => <a href="#contact" key={c.name} className="group rounded-xl border border-white bg-white p-5 transition hover:-translate-y-1 hover:shadow-lg"><span className={`grid h-11 w-11 place-items-center rounded-full ${c.color} text-xs font-bold text-white`}>{c.code}</span><h3 className="mt-10 font-bold group-hover:text-arshi-red">{c.name}</h3><p className="mt-1 text-xs text-stone-500">Explore options →</p></a>)}</div></div></section>

    <section id="stories" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="text-center"><p className="text-sm font-bold tracking-[.18em] text-arshi-red">REAL PEOPLE, REAL PROGRESS</p><h2 className="serif mt-3 text-4xl text-arshi-ink sm:text-5xl">Stories that start with trust.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[['“The process finally felt understandable.”','Nusrat J.','Study abroad, Malaysia'],['“We felt supported before we even left home.”','Rahim A.','China treatment coordination'],['“I found a plan that fits my career.”','Tania S.','Career counseling']].map(([quote, name, role]) => <figure key={name} className="rounded-xl border border-stone-200 p-7"><div className="text-xl text-arshi-orange">★★★★★</div><blockquote className="serif mt-5 text-2xl leading-snug text-arshi-ink">{quote}</blockquote><figcaption className="mt-8 border-t pt-4 text-sm"><b>{name}</b><span className="block mt-1 text-stone-500">{role}</span></figcaption></figure>)}</div></section>

    <section className="bg-[#F7F9F7] py-24"><div className="mx-auto grid max-w-4xl gap-12 px-5 md:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-bold tracking-[.18em] text-arshi-red">QUESTIONS, ANSWERED</p><h2 className="serif mt-3 text-4xl text-arshi-ink">Let’s make it clear.</h2><p className="mt-5 leading-7 text-[#657167]">If you need a more specific answer, our team is ready to help.</p></div><div>{faqs.map(([q, a]) => <details key={q} className="group border-b border-stone-200 py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-bold text-arshi-ink">{q}<span className="text-xl text-arshi-red group-open:rotate-45">+</span></summary><p className="mt-4 pr-8 text-sm leading-6 text-[#657167]">{a}</p></details>)}</div></div></section>

    <section id="contact" className="bg-arshi-red py-20"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[.85fr_1.15fr] lg:px-8"><div className="text-white"><p className="text-sm font-bold tracking-[.18em] text-[#FFD5CB]">TAKE THE FIRST STEP</p><h2 className="serif mt-3 text-5xl">Your future deserves a thoughtful beginning.</h2><p className="mt-6 max-w-md leading-7 text-white/80">Tell us where you want to go—or what support you need. We’ll help you find the right next step.</p><div className="mt-10 space-y-4 text-sm"><p><a href="tel:+8801818758882" className="hover:underline">☎ +880 1818-758882</a></p><p><a href="mailto:info@arshiglobalcare.com" className="hover:underline">✉ info@arshiglobalcare.com</a></p><p>⌖ Rajshahi Chamber of Commerce Building, Alokar More, Rajshahi</p></div></div><form className="rounded-xl bg-white p-6 sm:p-8" onSubmit={(e) => { e.preventDefault(); setSent(true); }}><h3 className="text-2xl font-bold">Book a free consultation</h3><p className="mt-2 text-sm text-stone-500">We usually respond within one working day.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><input required aria-label="Your name" placeholder="Your name" className="rounded-lg border border-stone-200 px-4 py-3 outline-none focus:border-arshi-red focus:ring-2 focus:ring-[#B42A1D]/15" /><input required type="tel" aria-label="Phone number" placeholder="Phone number" className="rounded-lg border border-stone-200 px-4 py-3 outline-none focus:border-arshi-red focus:ring-2 focus:ring-[#B42A1D]/15" /></div><select aria-label="Select a service" className="mt-4 w-full rounded-lg border border-stone-200 bg-white px-4 py-3 text-stone-500 outline-none focus:border-arshi-red"><option>Select a service</option>{services.map(s => <option key={s.title}>{s.title}</option>)}</select><textarea required aria-label="How can we help" placeholder="How can we help?" className="mt-4 min-h-[110px] w-full rounded-lg border border-stone-200 px-4 py-3 outline-none focus:border-arshi-red focus:ring-2 focus:ring-[#B42A1D]/15" /><button className="mt-4 w-full rounded-lg bg-arshi-ink px-5 py-4 font-bold text-white transition hover:bg-arshi-wine">{sent ? 'Thank you — we’ll be in touch.' : 'Send my request →'}</button></form></div></section>

    <footer className="bg-[#233124] py-14 text-[#D8E3DC]"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:grid-cols-2 lg:grid-cols-4 lg:px-8"><div><Logo /><p className="mt-5 max-w-xs text-sm leading-6">Thoughtful support for the global journeys that matter most.</p></div><div><h3 className="font-bold text-white">Explore</h3><div className="mt-4 grid gap-2 text-sm"><a href="#services">Our services</a><a href="#process">How it works</a><a href="#destinations">Destinations</a></div></div><div><h3 className="font-bold text-white">Services</h3><div className="mt-4 grid gap-2 text-sm"><a href="#services">Study abroad</a><a href="#services">China treatment package</a><a href="#services">Visa & immigration</a></div></div><div><h3 className="font-bold text-white">Stay connected</h3><p className="mt-4 text-sm">Follow guidance, stories and updates.</p><div className="mt-5 flex gap-2"><a href="#" aria-label="Facebook" className="grid h-9 w-9 place-items-center rounded-full border border-white/20 hover:bg-white hover:text-arshi-ink">f</a><a href="#" aria-label="Instagram" className="grid h-9 w-9 place-items-center rounded-full border border-white/20 hover:bg-white hover:text-arshi-ink">◎</a><a href="https://wa.me/8801818758882" target="_blank" rel="noopener noreferrer" aria-label="WhatsApp" className="grid h-9 w-9 place-items-center rounded-full border border-white/20 hover:bg-white hover:text-arshi-ink">◔</a></div></div></div><div className="mx-auto mt-12 max-w-7xl border-t border-white/10 px-5 pt-6 text-xs lg:px-8">© 2026 Arshi Global Care. All rights reserved.</div></footer>
  </main>;
}
